# Generated by Django 5.2.17 on 2026-09-25 12:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('donations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('mtn_momo', 'MTN Mobile Money'), ('orange_money', 'Orange Money')], max_length=20)),
                ('phone_number', models.CharField(max_length=20, verbose_name='Numéro Mobile Money')),
                ('amount', models.DecimalField(decimal_places=0, max_digits=12)),
                ('reference', models.CharField(max_length=50, unique=True)),
                ('status', models.CharField(choices=[('initiated', 'Initié'), ('success', 'Réussi'), ('failed', 'Échoué'), ('cancelled', 'Annulé')], default='initiated', max_length=10)),
                ('provider_response', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('contribution', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='donations.contribution')),
            ],
        ),
    ]
