# Generated by Django 5.2.17 on 2026-10-06 19:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0002_alter_partnershiprequest_organization'),
        ('payments', '0001_initial'),
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_ref', models.CharField(max_length=50, unique=True, verbose_name='Référence de paiement')),
                ('amount', models.DecimalField(decimal_places=0, max_digits=12, verbose_name='Montant (FCFA)')),
                ('phone_number', models.CharField(blank=True, default='', max_length=20, verbose_name='Numéro Mobile Money')),
                ('provider', models.CharField(blank=True, choices=[('mtn_momo', 'MTN Mobile Money'), ('orange_money', 'Orange Money')], default='', max_length=20)),
                ('status', models.CharField(choices=[('opened', 'Ouverte'), ('initiated', 'Initiée'), ('verified', 'Vérifiée'), ('failed', 'Échouée')], default='opened', max_length=10)),
                ('transaction_code', models.CharField(blank=True, max_length=100, verbose_name='Code de transaction')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('contribution', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_request', to='donations.contribution')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payment_requests', to='projects.project')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'project', 'created_at'], name='payments_pa_user_id_8e20aa_idx'), models.Index(fields=['phone_number', 'project', 'created_at'], name='payments_pa_phone_n_18fb84_idx')],
            },
        ),
    ]
