# Generated by Django 5.2.17 on 2026-09-25 06:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AlumniProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('graduation_year', models.PositiveIntegerField(verbose_name='Année de promotion')),
                ('profession', models.CharField(blank=True, max_length=150)),
                ('company', models.CharField(blank=True, max_length=150, verbose_name='Entreprise')),
                ('city', models.CharField(blank=True, max_length=100, verbose_name='Ville')),
                ('country', models.CharField(blank=True, default='Cameroun', max_length=100, verbose_name='Pays')),
                ('bio', models.TextField(blank=True)),
                ('skills', models.CharField(blank=True, max_length=255, verbose_name='Compétences')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='profiles/')),
                ('is_visible_in_directory', models.BooleanField(default=True, verbose_name="Visible dans l'annuaire")),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='alumni_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
