# Generated by Django 5.2.17 on 2026-09-26 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumni', '0002_membercard'),
    ]

    operations = [
        migrations.AddField(
            model_name='membercard',
            name='signature',
            field=models.ImageField(blank=True, null=True, upload_to='signatures/', verbose_name='Signature (tampon ou signature)'),
        ),
        migrations.AddField(
            model_name='membercard',
            name='signed_by',
            field=models.CharField(blank=True, help_text="Ex. Président de l'association", max_length=120, verbose_name='Signataire'),
        ),
    ]
