# Generated by Django 5.2.17 on 2026-09-25 07:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('objective', models.TextField(verbose_name='Objectif')),
                ('budget', models.DecimalField(decimal_places=0, max_digits=12, verbose_name='Budget estimé (FCFA)')),
                ('image', models.ImageField(blank=True, null=True, upload_to='projects/')),
                ('status', models.CharField(choices=[('draft', 'Brouillon'), ('active', 'En collecte'), ('funded', 'Financé'), ('completed', 'Réalisé')], default='draft', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
