# Generated by Django 5.2.17 on 2026-10-07 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(default='contact@megamightysixers.org', max_length=254)),
                ('phone', models.CharField(blank=True, default='+237 600 00 00 00', max_length=30)),
                ('whatsapp', models.CharField(blank=True, default='https://wa.me/237600000000', max_length=200)),
                ('address_en', models.CharField(blank=True, default='Cameroon', max_length=200)),
                ('address_fr', models.CharField(blank=True, default='Cameroun', max_length=200)),
                ('hours_en', models.CharField(blank=True, default='Monday to Saturday, 9 am — 5 pm', max_length=200)),
                ('hours_fr', models.CharField(blank=True, default='Lundi au samedi, 9 h — 17 h', max_length=200)),
                ('facebook', models.URLField(blank=True, default='https://facebook.com/megamightysixers')),
                ('twitter', models.URLField(blank=True, default='https://twitter.com/megamightysixers')),
                ('instagram', models.URLField(blank=True, default='https://instagram.com/megamightysixers')),
                ('youtube', models.URLField(blank=True, default='https://youtube.com/@megamightysixers')),
            ],
            options={
                'verbose_name': 'Informations de contact',
                'verbose_name_plural': 'Informations de contact',
            },
        ),
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(blank=True, max_length=200)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False, verbose_name='Lu')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
