# Generated by Django 5.2.17 on 2026-10-05 15:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actor_label', models.CharField(blank=True, help_text='Nom copie au moment de l action : le journal reste lisible meme si le compte est supprime ensuite.', max_length=150)),
                ('action', models.CharField(choices=[('create', 'Creation'), ('update', 'Modification'), ('delete', 'Suppression'), ('login', 'Connexion'), ('validate', 'Validation'), ('reject', 'Rejet'), ('publish', 'Publication'), ('backup', 'Sauvegarde')], max_length=20)),
                ('model_name', models.CharField(blank=True, max_length=100)),
                ('object_id', models.CharField(blank=True, max_length=64)),
                ('summary', models.CharField(blank=True, max_length=255)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Entree de journal',
                'verbose_name_plural': 'Journal d activite',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['model_name', 'object_id'], name='accounts_ac_model_n_91d77b_idx')],
            },
        ),
    ]
