# Generated by Django 5.2.17 on 2026-09-25 07:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('donor_name', models.CharField(max_length=150, verbose_name='Nom du donateur')),
                ('donor_email', models.EmailField(max_length=254, verbose_name='Email du donateur')),
                ('amount', models.DecimalField(decimal_places=0, max_digits=12, verbose_name='Montant (FCFA)')),
                ('method', models.CharField(choices=[('mtn_momo', 'MTN Mobile Money'), ('orange_money', 'Orange Money'), ('bank', 'Virement bancaire'), ('cash', 'Espèces'), ('other', 'Autre')], default='mtn_momo', max_length=20)),
                ('status', models.CharField(choices=[('pending', 'À confirmer'), ('confirmed', 'Confirmée'), ('rejected', 'Rejetée')], default='pending', max_length=10)),
                ('message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('donor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contributions', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contributions', to='projects.project')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PartnershipRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization', models.CharField(max_length=200, verbose_name='Organisation')),
                ('contact_name', models.CharField(max_length=150, verbose_name='Personne de contact')),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('partner_type', models.CharField(choices=[('company', 'Entreprise'), ('ngo', 'ONG / Association'), ('individual', 'Particulier'), ('public', 'Institution publique')], max_length=20)),
                ('message', models.TextField(verbose_name='Proposition')),
                ('status', models.CharField(choices=[('new', 'Nouvelle'), ('contacted', 'Contactée'), ('accepted', 'Acceptée'), ('refused', 'Refusée')], default='new', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='partnership_requests', to='projects.project')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
