# Generated by Django 5.2.17 on 2026-09-25 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partnershiprequest',
            name='organization',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Organisation (facultatif)'),
        ),
    ]
