# Generated by Django 5.2.17 on 2026-09-26 15:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # NOTE : quiz.course et le modèle Course sont supprimés en 0004,
        # après la conversion des données effectuée en 0003.
        migrations.AddField(
            model_name='quiz',
            name='title_fr',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='subject',
            name='color',
            field=models.CharField(default='#c9a227', help_text='Hex, ex. #e05252', max_length=9, verbose_name='Couleur de la matière'),
        ),
        migrations.AddField(
            model_name='subject',
            name='icon',
            field=models.CharField(default='mdi-book-outline', max_length=60, verbose_name='Icône (MDI)'),
        ),
        migrations.AddField(
            model_name='subject',
            name='slug',
            field=models.SlugField(max_length=120, null=True, unique=True),
        ),
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=1)),
                ('title', models.CharField(max_length=200, verbose_name='Titre (anglais prioritaire)')),
                ('title_fr', models.CharField(blank=True, max_length=200, verbose_name='Titre (français)')),
                ('description', models.TextField(blank=True)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chapters', to='education.subject')),
            ],
            options={
                'ordering': ['subject', 'order'],
            },
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=1)),
                ('kind', models.CharField(choices=[('lesson', 'Leçon'), ('exam_paper', "Ancien sujet d'examen")], default='lesson', max_length=12)),
                ('title', models.CharField(max_length=200)),
                ('title_fr', models.CharField(blank=True, max_length=200, verbose_name='Titre (français)')),
                ('summary', models.TextField(blank=True, verbose_name='Résumé (anglais)')),
                ('summary_fr', models.TextField(blank=True, verbose_name='Résumé (français)')),
                ('content', models.TextField(blank=True, verbose_name='Cours (Markdown, anglais)')),
                ('content_fr', models.TextField(blank=True, verbose_name='Cours (Markdown, français)')),
                ('video_url', models.URLField(blank=True, verbose_name='Vidéo YouTube principale')),
                ('estimated_minutes', models.PositiveIntegerField(default=20, verbose_name='Durée estimée (min)')),
                ('status', models.CharField(choices=[('draft', 'Brouillon'), ('pending', 'En attente de validation'), ('published', 'Publié')], default='draft', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='education.chapter')),
                ('teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lessons', to=settings.AUTH_USER_MODEL, verbose_name='Auteur')),
            ],
            options={
                'ordering': ['chapter', 'order'],
            },
        ),
        migrations.AddField(
            model_name='quiz',
            name='lesson',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quizzes', to='education.lesson'),
        ),
        migrations.CreateModel(
            name='LessonProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed_at', models.DateTimeField(auto_now_add=True)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress', to='education.lesson')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson_progress', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-completed_at'],
                'unique_together': {('lesson', 'student')},
            },
        ),
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=1)),
                ('kind', models.CharField(choices=[('video', 'Vidéo'), ('pdf', 'PDF'), ('link', 'Lien externe'), ('exam_paper', "Ancien sujet d'examen")], default='link', max_length=12)),
                ('title', models.CharField(max_length=200)),
                ('title_fr', models.CharField(blank=True, max_length=200)),
                ('url', models.URLField(blank=True, verbose_name='Lien externe')),
                ('file', models.FileField(blank=True, null=True, upload_to='resources/', verbose_name='Fichier hébergé (PDF libre de droits)')),
                ('source_name', models.CharField(blank=True, max_length=150, verbose_name='Source')),
                ('license_note', models.CharField(blank=True, max_length=200, verbose_name='Licence / attribution')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resources', to='education.lesson')),
            ],
            options={
                'ordering': ['lesson', 'order'],
            },
        ),
        # DeleteModel('Course') reporté en 0004 (après conversion interne 0003).
    ]
