# Generated by Django 5.2.17 on 2026-09-26 15:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0004_cleanup_legacy_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chapter',
            name='title_fr',
            field=models.CharField(blank=True, max_length=200, verbose_name='Titre (franÃ§ais)'),
        ),
        migrations.AlterField(
            model_name='choice',
            name='is_correct',
            field=models.BooleanField(default=False, verbose_name='Bonne rÃ©ponse'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='content_fr',
            field=models.TextField(blank=True, verbose_name='Cours (Markdown, franÃ§ais)'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='estimated_minutes',
            field=models.PositiveIntegerField(default=20, verbose_name='DurÃ©e estimÃ©e (min)'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='kind',
            field=models.CharField(choices=[('lesson', 'LeÃ§on'), ('exam_paper', "Ancien sujet d'examen")], default='lesson', max_length=12),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='status',
            field=models.CharField(choices=[('draft', 'Brouillon'), ('pending', 'En attente de validation'), ('published', 'PubliÃ©')], default='draft', max_length=10),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='summary',
            field=models.TextField(blank=True, verbose_name='RÃ©sumÃ© (anglais)'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='summary_fr',
            field=models.TextField(blank=True, verbose_name='RÃ©sumÃ© (franÃ§ais)'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='title_fr',
            field=models.CharField(blank=True, max_length=200, verbose_name='Titre (franÃ§ais)'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='video_url',
            field=models.URLField(blank=True, verbose_name='VidÃ©o YouTube principale'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='lesson',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quizzes', to='education.lesson'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='pass_score',
            field=models.PositiveIntegerField(default=50, verbose_name='Score de rÃ©ussite (%)'),
        ),
        migrations.AlterField(
            model_name='quizattempt',
            name='score',
            field=models.PositiveIntegerField(verbose_name='Bonnes rÃ©ponses'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='resources/', verbose_name='Fichier hÃ©bergÃ© (PDF libre de droits)'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='kind',
            field=models.CharField(choices=[('video', 'VidÃ©o'), ('pdf', 'PDF'), ('link', 'Lien externe'), ('exam_paper', "Ancien sujet d'examen")], default='link', max_length=12),
        ),
        migrations.AlterField(
            model_name='subject',
            name='color',
            field=models.CharField(default='#c9a227', help_text='Hex, ex. #e05252', max_length=9, verbose_name='Couleur de la matiÃ¨re'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='icon',
            field=models.CharField(default='mdi-book-outline', max_length=60, verbose_name='IcÃ´ne (MDI)'),
        ),
    ]
