# Generated by Django 5.2.17 on 2026-09-30 15:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0005_alter_chapter_title_fr_alter_choice_is_correct_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='image_url',
            field=models.URLField(blank=True, default='', help_text='URL hotlink (Wikimedia Commons, libre de droits)', verbose_name='Image de couverture'),
        ),
        migrations.AlterField(
            model_name='chapter',
            name='title_fr',
            field=models.CharField(blank=True, max_length=200, verbose_name='Titre (français)'),
        ),
        migrations.AlterField(
            model_name='choice',
            name='is_correct',
            field=models.BooleanField(default=False, verbose_name='Bonne réponse'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='content_fr',
            field=models.TextField(blank=True, verbose_name='Cours (Markdown, français)'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='estimated_minutes',
            field=models.PositiveIntegerField(default=20, verbose_name='Durée estimée (min)'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='kind',
            field=models.CharField(choices=[('lesson', 'Leçon'), ('exam_paper', "Ancien sujet d'examen")], default='lesson', max_length=12),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='status',
            field=models.CharField(choices=[('draft', 'Brouillon'), ('pending', 'En attente de validation'), ('published', 'Publié')], default='draft', max_length=10),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='summary',
            field=models.TextField(blank=True, verbose_name='Résumé (anglais)'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='summary_fr',
            field=models.TextField(blank=True, verbose_name='Résumé (français)'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='title_fr',
            field=models.CharField(blank=True, max_length=200, verbose_name='Titre (français)'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='video_url',
            field=models.URLField(blank=True, verbose_name='Vidéo YouTube principale'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='lesson',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='quizzes', to='education.lesson'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='quiz',
            name='pass_score',
            field=models.PositiveIntegerField(default=50, verbose_name='Score de réussite (%)'),
        ),
        migrations.AlterField(
            model_name='quizattempt',
            name='score',
            field=models.PositiveIntegerField(verbose_name='Bonnes réponses'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='resources/', verbose_name='Fichier hébergé (PDF libre de droits)'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='kind',
            field=models.CharField(choices=[('video', 'Vidéo'), ('pdf', 'PDF'), ('link', 'Lien externe'), ('exam_paper', "Ancien sujet d'examen")], default='link', max_length=12),
        ),
        migrations.AlterField(
            model_name='subject',
            name='color',
            field=models.CharField(default='#c9a227', help_text='Hex, ex. #e05252', max_length=9, verbose_name='Couleur de la matière'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='icon',
            field=models.CharField(default='mdi-book-outline', max_length=60, verbose_name='Icône (MDI)'),
        ),
    ]
