# Generated by Django 5.2.17 on 2026-10-01 14:13

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0007_lesson_objectives_question_explanation_tutormessage'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='config',
            field=models.JSONField(blank=True, default=dict, help_text='numeric: {accepted:[..], tolerance:n} | text: {accepted:[..], case_sensitive:false} | ordered: {items:[..]} | pairing: {pairs:[[a,b]]}', verbose_name='Règle de correction selon le type'),
        ),
        migrations.AddField(
            model_name='question',
            name='difficulty',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='Difficulté (1-3)'),
        ),
        migrations.AddField(
            model_name='question',
            name='hint_prompt',
            field=models.CharField(blank=True, max_length=200, verbose_name='Question affichée avant les indices'),
        ),
        migrations.AddField(
            model_name='question',
            name='kind',
            field=models.CharField(choices=[('mcq', 'Choix multiples'), ('numeric', 'Réponse numérique'), ('text', 'Texte court'), ('ordered', 'Remise en ordre'), ('pairing', 'Appariement')], default='mcq', max_length=12),
        ),
        migrations.AlterField(
            model_name='question',
            name='quiz',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='education.quiz'),
        ),
        migrations.CreateModel(
            name='Concept',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=1)),
                ('title', models.CharField(max_length=200)),
                ('title_fr', models.CharField(blank=True, max_length=200)),
                ('bloom_level', models.CharField(choices=[('remember', 'Mémoriser'), ('understand', 'Comprendre'), ('apply', 'Appliquer'), ('analyze', 'Analyser'), ('evaluate', 'Évaluer')], default='understand', max_length=12)),
                ('required', models.BooleanField(default=True)),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='concepts', to='education.chapter')),
            ],
            options={
                'ordering': ['chapter', 'order'],
            },
        ),
        migrations.CreateModel(
            name='ExerciseAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('given', models.JSONField(blank=True, default=dict, verbose_name='Réponse donnée')),
                ('is_correct', models.BooleanField(default=False)),
                ('is_first_try', models.BooleanField(default=True, verbose_name='Bonne du premier coup')),
                ('hints_used', models.PositiveIntegerField(default=0)),
                ('tries', models.PositiveIntegerField(default=1)),
                ('time_spent_ms', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='education.question')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercise_attempts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Hint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=1)),
                ('text', models.TextField()),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hints', to='education.question')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Step',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=1)),
                ('kind', models.CharField(choices=[('concept', 'Nouveau concept'), ('explain', 'Explication'), ('example', 'Exemple résolu'), ('practice', 'Exercice guidé'), ('question', 'Vérification'), ('summary', 'Bilan')], default='concept', max_length=12)),
                ('title', models.CharField(blank=True, max_length=200)),
                ('content', models.TextField(blank=True, verbose_name='Contenu court (Markdown)')),
                ('video_url', models.URLField(blank=True)),
                ('image_url', models.URLField(blank=True)),
                ('required', models.BooleanField(default=False, verbose_name='Doit être réussi pour valider la leçon')),
                ('xp', models.PositiveIntegerField(default=10)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='education.lesson')),
                ('question', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='step', to='education.question')),
            ],
            options={
                'ordering': ['lesson', 'order'],
            },
        ),
        migrations.CreateModel(
            name='ConceptState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('box', models.PositiveSmallIntegerField(default=0)),
                ('strength', models.FloatField(default=0.0, verbose_name='Force estimée (0-1)')),
                ('seen_count', models.PositiveIntegerField(default=0)),
                ('correct_count', models.PositiveIntegerField(default=0)),
                ('due_at', models.DateField(default=django.utils.timezone.localdate)),
                ('last_seen', models.DateTimeField(blank=True, null=True)),
                ('concept', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='states', to='education.concept')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='concept_states', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['due_at'],
                'unique_together': {('student', 'concept')},
            },
        ),
        migrations.CreateModel(
            name='LessonMastery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('validated', models.PositiveIntegerField(default=0)),
                ('required', models.PositiveIntegerField(default=0)),
                ('mastered_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mastery', to='education.lesson')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson_mastery', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('student', 'lesson')},
            },
        ),
    ]
