# Generated by Django 5.2.17 on 2026-10-01 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0008_question_config_question_difficulty_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='choice',
            name='text_fr',
            field=models.CharField(blank=True, max_length=300, verbose_name='Choix (français)'),
        ),
        migrations.AddField(
            model_name='hint',
            name='text_fr',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='lesson',
            name='objectives_fr',
            field=models.JSONField(blank=True, default=list, verbose_name="Objectifs d'apprentissage (français)"),
        ),
        migrations.AddField(
            model_name='question',
            name='explanation_fr',
            field=models.TextField(blank=True, verbose_name='Explication (français)'),
        ),
        migrations.AddField(
            model_name='question',
            name='hint_prompt_fr',
            field=models.CharField(blank=True, max_length=200, verbose_name='Question avant indices (français)'),
        ),
        migrations.AddField(
            model_name='question',
            name='text_fr',
            field=models.TextField(blank=True, verbose_name='Question (français)'),
        ),
        migrations.AddField(
            model_name='step',
            name='content_fr',
            field=models.TextField(blank=True, verbose_name='Contenu court (Markdown, français)'),
        ),
        migrations.AddField(
            model_name='step',
            name='title_fr',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
