# Generated by Django 5.2.17 on 2026-10-05 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0009_choice_text_fr_hint_text_fr_lesson_objectives_fr_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='is_public',
            field=models.BooleanField(default=False, help_text="§4 et §10 : le visiteur doit pouvoir consulter les ressources educatives « selectionnees ». Par defaut NON, parce qu ouvrir toute la pedagogie au public est une decision de l'association, pas un effet de bord du statut publie. L'enseignant ou l'admin coche la lecon qu il souhaite exposer.", verbose_name='Accessible sans compte'),
        ),
    ]
