"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.2.17.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'
BASE_DIR = Path(__file__).resolve().parent.parent


def _vrai(valeur, defaut=False):
    """Lit un booleen d'environnement sans surprise.

    `bool('0')` vaut True en Python : une variable valant « 0 » ou « false »
    activerait donc l'option alors qu'elle est censee la desactiver. On compare
    explicitement, sinon un deploiement mal configure se croit en production
    secure alors qu'il ne l'est pas.
    """
    if valeur is None:
        return defaut
    return valeur.strip().lower() in ('1', 'true', 'oui', 'yes', 'on')


def _liste(valeur, defaut=()):
    if not valeur:
        return list(defaut)
    return [m.strip() for m in valeur.split(',') if m.strip()]


def _hotes_locaux():
    """Les adresses par lesquelles la meme machine peut etre atteinte.

    En developpement on ouvre le site depuis le telephone pose sur le meme
    reseau. Son hote, c'est l'IP de la machine de dev — pas `localhost`, qui
    depuis le telephone designerait le telephone lui-meme.
    """
    adresses = {'localhost', '127.0.0.1', 'testserver', '0.0.0.0'}
    try:
        import socket
        adresses.add(socket.gethostbyname(socket.gethostname()))
        for info in socket.getaddrinfo(socket.gethostname(), None, socket.AF_INET):
            adresses.add(info[4][0])
    except OSError:
        # Sans reseau, on retombe sur les hôtes de base : le site reste
        # ouvrable en local, c'est le cas le plus courant.
        pass
    return sorted(adresses)


# --- Environnement ---
# Un fichier .env local est charge si present, pour ne pas avoir a exporter les
# variables a la main a chaque demarrage. Il est lu sans dependance externe et
# ne remplace pas les variables reellement definies.
_FICHIER_ENV = BASE_DIR / '.env'
if _FICHIER_ENV.exists():
    for _ligne in _FICHIER_ENV.read_text(encoding='utf-8').splitlines():
        _ligne = _ligne.strip()
        if not _ligne or _ligne.startswith('#') or '=' not in _ligne:
            continue
        _cle, _valeur = _ligne.split('=', 1)
        os.environ.setdefault(_cle.strip(), _valeur.strip().strip('"').strip("'"))


EN_PRODUCTION = not _vrai(os.environ.get('DEBUG'), True)

# Cle secrete identique en local et en production : le projet n'est pas sensible
# et on garde la meme valeur partout pour ne pas invalider les jetons JWT deja
# emis. Une variable d'environnement SECRET_KEY reste prioritaire si definie.
SECRET_KEY = os.environ.get('SECRET_KEY') or (
    'django-insecure-r&_r!+=nsr2d^2r#$og9$^r6x+vfq*#=$1b*%myfckrrypil%)'
)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = not EN_PRODUCTION

ALLOWED_HOSTS = _liste(
    os.environ.get('ALLOWED_HOSTS'),
    # En developpement, on accepte aussi l'IP locale : c'est depuis le
    # telephone pose sur le meme reseau qu'on ouvre le site en test.
    # En production l'hote doit etre fourni, sinon Django ne sert a personne.
    (['localhost', '127.0.0.1', 'testserver'] + _hotes_locaux()) if DEBUG else [],
)
if not ALLOWED_HOSTS:
    raise RuntimeError(
        'ALLOWED_HOSTS est obligatoire quand DEBUG=false '
        '(exemple : ALLOWED_HOSTS=megamighty-sixers.org).'
    )


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    # 3rd party
    'rest_framework',
    'rest_framework_simplejwt',
    'corsheaders',
    # Apps projets
    'accounts',
    'alumni',
    'events',
    'news',
    'archives',
    'projects',
    'donations',
    'notifications',
    'education',
    'payments',
    'mentorship',
    'contact',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# --- Mega Mighty Sixers ---
from datetime import timedelta

AUTH_USER_MODEL = 'accounts.User'

# Base de données : DATABASE_URL (Neon) en priorite, sinon variables POSTGRES_*,
# sinon SQLite (dev)
if os.environ.get('DATABASE_URL'):
    from urllib.parse import parse_qsl, urlparse
    _url = urlparse(os.environ['DATABASE_URL'])
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': _url.path.lstrip('/'),
            'USER': _url.username,
            'PASSWORD': _url.password,
            'HOST': _url.hostname,
            'PORT': _url.port or 5432,
            # sslmode=require et channel_binding=require sont lus ici (Neon)
            'OPTIONS': dict(parse_qsl(_url.query)),
            'CONN_MAX_AGE': 60,
        }
    }
elif os.environ.get('POSTGRES_DB'):
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': os.environ.get('POSTGRES_DB'),
            'USER': os.environ.get('POSTGRES_USER'),
            'PASSWORD': os.environ.get('POSTGRES_PASSWORD'),
            'HOST': os.environ.get('POSTGRES_HOST', 'localhost'),
            'PORT': os.environ.get('POSTGRES_PORT', '5432'),
        }
    }

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticatedOrReadOnly',
    ),
}

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(hours=2),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=3650),
}

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# --- Paiement Mobile Money (flux SaveNow) ---
# PAYMENT_SIMULATION : en simulation, un code de transaction d'au moins
# 4 caractères valide la demande ; en production il faudra brancher un vrai
# provider (MTN/Orange) qui vérifie le code reçu par SMS.
PAYMENT_SIMULATION = _vrai(os.environ.get('PAYMENT_SIMULATION'), True)
PAYMENT_BENEFICIARY = os.environ.get('PAYMENT_BENEFICIARY', 'Mega Mighty Sixers')
PAYMENT_DAILY_LIMIT = int(os.environ.get('PAYMENT_DAILY_LIMIT', '3'))
PAYMENT_MIN_AMOUNT = 500
# Codes marchands affichés dans les codes USSD à composer côté téléphone.
MERCHANT_MTN_CODE = os.environ.get('MERCHANT_MTN_CODE', '1234567')
MERCHANT_ORANGE_CODE = os.environ.get('MERCHANT_ORANGE_CODE', '7654321')

# --- Sécurité du transport (§9) ---
# HTTPS est obligatoire en production : sans cela, un jeton JWT d'un membre peut
# etre lu en clair sur un reseau ouvert (Wi-Fi d'un etablissement, operateur
# mobile). Les options restent desactives en local, sinon le developpement sur
# http://localhost deviendrait impossible.

SECURE_SSL_REDIRECT = _vrai(os.environ.get('SECURE_SSL_REDIRECT'), EN_PRODUCTION)
SESSION_COOKIE_SECURE = _vrai(os.environ.get('SESSION_COOKIE_SECURE'), EN_PRODUCTION)
CSRF_COOKIE_SECURE = _vrai(os.environ.get('CSRF_COOKIE_SECURE'), EN_PRODUCTION)
SECURE_HSTS_SECONDS = int(os.environ.get('SECURE_HSTS_SECONDS', '0' if DEBUG else '31536000'))
SECURE_HSTS_INCLUDE_SUBDOMAINS = _vrai(
    os.environ.get('SECURE_HSTS_INCLUDE_SUBDOMAINS'), EN_PRODUCTION
)
SECURE_HSTS_PRELOAD = _vrai(os.environ.get('SECURE_HSTS_PRELOAD'), False)
SECURE_CONTENT_TYPE_NOSNIFF = True
SECURE_REFERRER_POLICY = 'strict-origin-when-cross-origin'
# Django >= 4 : le nom d'hote doit etre autorise a presenter un certificat.
# 'auto' suffit quand un reverse-proxy (Nginx, Caddy) gere le TLS.
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
USE_X_FORWARDED_HOST = EN_PRODUCTION
X_FRAME_OPTIONS = 'DENY'

# Origines autorisees a presenter des jetons : sans cela, un site tiers peut
# rejouer une requete contre l'API au nom de membre connecte.
CSRF_TRUSTED_ORIGINS = _liste(os.environ.get('CSRF_TRUSTED_ORIGINS'))
CORS_ALLOWED_ORIGINS = _liste(
    os.environ.get('CORS_ALLOWED_ORIGINS'),
    # En developpement le front est ouvert depuis n'importe quelle adresse de
    # la machine : `localhost` sur la machine, et l'IP locale depuis le
    # telephone. Plutot que de maintenir une liste qui change a chaque reseau,
    # on ouvre en dev.
    [] if EN_PRODUCTION else ['http://localhost:5173', 'http://127.0.0.1:5173'],
)
# Pendant la mise en place, l'app pelou deja presente sur le serveur accepte
# toute origine et ce backend doit se comporter pareil. On ouvre donc CORS a
# tout le monde, en dev comme en production. Pour resserrer plus tard : definir
# CORS_ALLOW_ALL=false et fournir CORS_ALLOWED_ORIGINS.
CORS_ALLOW_ALL_ORIGINS = _vrai(os.environ.get('CORS_ALLOW_ALL'), True)
if not CORS_ALLOWED_ORIGINS:
    # Pas une erreur fatale : une PWA servie par le meme hote n'a pas besoin de
    # CORS. On garde une liste vide plutot que None pour rester sur.
    CORS_ALLOWED_ORIGINS = []

# --- Emails ---
# En developpement, EMAIL_BACKEND=console : les emails s'impriment dans le
# terminal du serveur au lieu d'etre envoyes (aucun compte SMTP requis).
# En production, definir EMAIL_BACKEND smtp + EMAIL_HOST/USER/PASSWORD.
EMAIL_BACKEND = os.environ.get(
    'EMAIL_BACKEND',
    'django.core.mail.backends.console.EmailBackend' if DEBUG
    else 'django.core.mail.backends.smtp.EmailBackend',
)
EMAIL_HOST = os.environ.get('EMAIL_HOST', '')
EMAIL_PORT = int(os.environ.get('EMAIL_PORT', '587'))
EMAIL_HOST_USER = os.environ.get('EMAIL_HOST_USER', '')
EMAIL_HOST_PASSWORD = os.environ.get('EMAIL_HOST_PASSWORD', '')
EMAIL_USE_TLS = _vrai(os.environ.get('EMAIL_USE_TLS'), True)
DEFAULT_FROM_EMAIL = os.environ.get(
    'DEFAULT_FROM_EMAIL', 'Mega Mighty Sixers <noreply@megamighty-sixers.org>'
)

# URL publique du front : construite dans les emails et les poussées web.
FRONTEND_URL = os.environ.get('FRONTEND_URL', 'http://localhost:5173').rstrip('/')

# --- Web Push (spec VAPID) ---
# VAPID_PRIVATE_KEY : chemin vers la cle privee PEM (generee une fois, jamais
# versionnee — voir .env.example). Sans cle, les poussées sont simplement
# ignorees : le reste des notifications continue de fonctionner.
VAPID_PRIVATE_KEY = os.environ.get('VAPID_PRIVATE_KEY', '')
VAPID_PUBLIC_KEY = os.environ.get('VAPID_PUBLIC_KEY', '')
# Contact obligatoire dans les claims VAPID (mailto: ou https:).
VAPID_CONTACT = os.environ.get('VAPID_CONTACT', 'mailto:alphonseessomba60@gmail.com')

# --- Templates ---
TEMPLATES[0]['DIRS'] = [BASE_DIR / 'templates']
